spring:
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: "${GOOGLE_CLIENT_ID}"
                client-secret: "${GOOGLE_CLIENT_SECRET}"

  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"

  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  jwt:
    secret-key: "${JWT_SECRET_KEY}"
    expiration-time:
      access: 900000
      refresh: 1296000000

  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "${SUPPORT_EMAIL}"
    password: "${APP_PASSWORD}"

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  api:
    url: "http://localhost:8080"

  config:
    import: "optional:file:.env[.properties]"

server:
  port: 8081